site_name: BinBuffer docs
site_description: Docs
site_author: super_sonic

extra_javascript:
  - highlight.js

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy 
  palette:
    - scheme: slate 
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light theme

    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark theme

nav:
  - Main: index.md
  - Getting Started:
    - installation: guides/installation.md
  - API:
    - reference: api/reference.md


plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GameF200/
